name: MindLoopEVO AutoDeploy
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */12 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install and Run MindLoop
        run: |
          echo "🚀 MindLoopEVO IA Autónoma activada"
          echo "Analizando mejoras..."
          echo "Optimizando rendimiento y economía..."
